### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by gkubisa** [evancz/elm-html#106]
Tested in Chrome Version 49.0.2623.87 (64-bit) on Ubuntu 14.04

Reproducible 100% using the code below:
```
module Leak where

import Html exposing (b, i, text)
import Time exposing (every, millisecond)
import Signal

main = Signal.map (viewNumber << round) <| every (11 * millisecond)

viewNumber number =
  if number % 2 == 0
    then b [] [ text <| (toString number) ++ " is even" ]
    else i [] [ text <| (toString number) ++ " is odd" ]
```

Recording the timeline for 1 minute yields the following result:

![screen shot](http://s10.postimg.org/g6ugxapt5/Leak.png)

**Comment by gkubisa** [comment]
Sorry, it seems that the DOM nodes and the memory are eventually released, although it may take a significant amount of time - many minutes. The number of DOM nodes can also reach over 8000, before they are GCed.

**Comment by evancz** [comment]
Interesting. How do you know how many DOM nodes are sitting around? Is that the green line?

I know projects used to recycle DOM nodes because certain browsers used to *never* free them. Not sure if that is still a useful idea anymore. If the GC cycle of normal JS values and DOM nodes are decoupled, it's not clear if there'd be a net performance improvement with more tricks.

**Comment by gkubisa** [comment]
Yes, the green line shows the number of DOM nodes.

Regarding the browsers leaking the DOM nodes, it looks like it was a problem for IE<10. Considering that Microsoft supports only IE>=11, I think Elm could do the same and thus not worry about those leaks.

References:
- [IE<10 end of support](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support)
- [memory leaks in IE](http://com.hemiola.com/2009/11/23/memory-leaks-in-ie8/)
- [more memory leaks in IE](http://javascript.info/tutorial/memory-leaks#circular-references-collection)
- [mark-and-sweep GC used in modern browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#Mark-and-sweep_algorithm)

As I understand, https://github.com/Matt-Esch/virtual-dom is responsible for reusing the DOM nodes as much as possible. However, it is not keeping around the DOM nodes which are not _currently_ needed, with the view of reusing them later - as evidenced by the increasing number of nodes in my test case from the previous post. IMHO, this is the right behaviour because it does not assume that the programmer wants to trade memory for speed, and I believe the same should apply to Elm.

I think that in the rare cases where the overhead of DOM node creation is too large, the _currently redundant_ nodes can be simply hidden using `display: none` style, and then shown again later as needed, for example:

```
module Leak where

import Html exposing (b, i, span, text)
import Html.Attributes exposing (style)
import Time exposing (every, millisecond)
import Signal

main = Signal.map (viewNumber << round) <| every (511 * millisecond)

viewNumber number =
  span [] 
    [ b (hideIfOdd number) [ text <| (toString number) ++ " is even" ]
    , i (hideIfEven number) [ text <| (toString number) ++ " is odd" ]
    ]
    
hideIfOdd number =
  if number % 2 == 0
    then []
    else [ style [("display", "none")] ]
    
hideIfEven number =
  if number % 2 == 0
    then [ style [("display", "none")] ]
    else []
```
