### ISSUE TITLE
can't install elm-html with latest version of elm.

### ISSUE THREAD

**Issue by empath** [evancz/elm-html#113]
```
elm-package install evancz/elm-html
To install evancz/elm-html I would like to add the following
dependency to elm-package.json:

    "evancz/elm-html": "4.0.2 <= v < 5.0.0"

May I add that to elm-package.json for you? (y/n) y


Error: Unable to find a set of packages that will work with your constraints.

# cat elm-package.json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 5.0.0",
        "evancz/elm-html": "4.0.2 <= v < 5.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
```

**Comment by evancz** [comment]
This package has moved to `elm-lang/html` like it says in https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md

**Comment by empath** [comment]
Can you include this in the guide?  There's absolutely no instructions whatsoever for how to install the html package, but you use it in the examples.  I had to google how to install it, and came up with the old library.

**Comment by evancz** [comment]
Sorry for the trouble. Where in the guide specifically would it be most helpful?

**Comment by empath** [comment]
I think probably just a quick section at the beginning on how to use elm package and where to find the packages before you get into any examples that require them?
