### ISSUE TITLE
Support 0.17.0 of Elm

### ISSUE THREAD

**Issue by howdoicomputer** [evancz/elm-html#114]
I just started a new Elm project completely fresh and got the package constraints message I've been seeing in other closed issues.

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 5.0.0",
        "evancz/elm-html": "4.0.2 <= v < 5.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}
```

Does this have something to do with the recent release of `0.17.0`?

**Comment by howdoicomputer** [comment]
Yeah, looks like it. Both `elm-html` and `virtual-dom` have package constraints pinned against Elm `0.16.0`. I started to fork both and upload them so I can unblock my experimentation but it looks like there were some problems...

```
λ elm package publish
Verifying howdoicomputer/virtual-dom 2.1.1 ...

Error: failure when running: elm-make --yes --docs=elm-stuff\documentation.json --prepublish
Downloading elm-lang/core
Packages configured successfully!
-- SYNTAX PROBLEM ----------------------------------------- .\src\VirtualDom.elm

I ran into something unexpected when parsing your code!

2|     ( Node
       ^
I am looking for one of the following things:

    something like `exposing (..)` which replaced `where` in 0.17
    whitespace
```

**Comment by torresmi** [comment]
Looks like `evancz/elm-html` has been moved to `elm-lang/html`. Replacing that dependency with `"elm-lang/html": "1.0.0 <= v < 2.0.0"` should fix it.

**Comment by howdoicomputer** [comment]
@torresmi Ah, neat! Thanks for chiming in. That super worked. Maybe a deprecation warning for this repository then? I picked a newish looking guide for working with Elm and it led me to this dependency and nothing really told me otherwise.

Again, thank you for pointing me in the right direction.

**Comment by evancz** [comment]
Added a note in the README about how this is deprecated. Will take more serious action in a different way.

**Comment by howdoicomputer** [comment]
Thanks @evancz
