### ISSUE TITLE
Show deprecation notice and link on the package page

### ISSUE THREAD

**Issue by danneu** [evancz/elm-html#119]
I think it'd help people out if http://package.elm-lang.org/packages/evancz/elm-html/4.0.2 had a deprecation notice and linked to the new package.

That page is the 1st google result for "elm html" and I've caught myself flipping through it multiple times before realizing I was on the wrong package. The other `evancz/*` packages that were moved to `elm-lang/*` could use the same treatment to avoid confusion.

**Comment by evancz** [comment]
Google has not improved over time, so I switched it

http://package.elm-lang.org/packages/evancz/elm-html/5.0.0/

Thanks for the suggestion!
