### ISSUE TITLE
webkit-playsinline attribute doesn't want to appear

### ISSUE THREAD

**Issue by Zinggi** [evancz/elm-html#15]
if I do either:
```Haskell
toggle "webkit-playsinline" True
```
or
```Haskell
attr "webkit-playsinline" "true"
```
nothing happens, it doesn't appear as an attribute, it is simply ignored.

**Comment by evancz** [comment]
@rehno-lindeque added the `attribute` function which should cover this case. I haven't released it yet, but it should be coming!

**Comment by evancz** [comment]
It is released, thanks for the report and the pointers!
