### ISSUE TITLE
Add record getters for Html type

### ISSUE THREAD

**Issue by twifkak** [evancz/elm-html#16]
Hi! Just started playing with Elm & elm-html for the first time. First thing I wanted to do was abstract behavior from presentation. I've got a `clicks : Input ()` and a `toggle : Signal Bool` derived from that, and I'd like to turn this:

    ...
    h2 [style [prop "-webkit-user-select" "none"],
        onclick clicks.handle <| always ()] [text "Heading"],
    div [style [showIf toggle]] [text "Body"]
    ...

into this:

    ...
    h2 [] [text "Heading"] |> toggler clicks,
    div [] [text "Body"] |> togglee toggle
    ...

and have all of the plumbing hidden away. This is dependent on being able to write an Html -> Html transformer, which is dependent on being able to deconstruct the behind-the-scenes record type.

**Comment by evancz** [comment]
I don't think the elm-html library should address this case. I definitely see what you are saying, but I think having a "HTML builder" on top of the core stuff is a better route.

I want to keep this API as simple as possible, and I am pretty confident the behavior you want can be built on top of the existing API.

**Comment by twifkak** [comment]
It seems like unnecessary complexity to have another library, with a new set of types that must be kept in sync with the existing ones. Adding getters to the existing Node type in VirtualDom.js seems like a much simpler solution. Obviously, it's up to you, though. I haven't used Elm since last November, so I have no dog in this fight.
