### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by dubiousdavid** [evancz/elm-html#26]
http://package.elm-lang.org/packages/evancz/elm-html/1.0.0/Html-Attributes#class

The docs for class discuss the "attribute" function.

**Comment by ThomasWeiser** [comment]
This let me also very puzzled on first sight:

    import Json.Encode (string)
    
    greeting : Html
    greeting =
        div [ attribute "class" (string "greeting") ] [
          text "Hello!"
        ]

I think it should read:

    import Html.Attributes (class)
    
    greeting : Html
    greeting =
        div [ class "greeting" ] [
          text "Hello!"
        ]

**Comment by evancz** [comment]
Something was odd with the documentation, it was getting paired with the wrong function. Should be fixed in the latest release. Thanks for the report!
