### ISSUE TITLE
Can't click on links or buttons when rendering at a high framerate

### ISSUE THREAD

**Issue by gsingh93** [evancz/elm-html#34]
I'm not sure if this is feasible or even practical, but I had some code like this:

```
import Html (Html, fromElement)
import Graphics.Element (Element, spacer)
import Signal (Signal, (<~))
import Time (fps)
import Text (centered, link, fromString)
    
main : Signal Html
main = fromElement <~ (view <~ fps 60)

view : Float -> Element
view f = centered <| link "http://google.com" <| fromString "google.com"
```
but I couldn't click on the link because of the high fps. Changing the fps to something lower like 1 does work. The reason the framerate was high to begin with is because I was working on some animations.

**Comment by evancz** [comment]
The underlying has been reported a few different ways, so I'm combining them all into meta issue #80. Follow along there to see progress on this. Thanks for the report!
