### ISSUE TITLE
Weird behavior with Html varying over a Signal containing Array

### ISSUE THREAD

**Issue by rehno-lindeque** [evancz/elm-html#35]
Sorry, I know this is a vague issue. I will try to refine the problem if I manage to get a chance later. Please feel free to close it if this is too vague for now.

These two functions print the same output to the log, but results in different Html when `{query, matches}` changes (on a signal).

Correct Html output:
```elm
ul p {query, matches} =
  Html.ul []
    <| List.map
        (\m -> 
          Html.li [ class' p.liClass ] [ p.config.renderItem m ]
        )
        (Debug.log "list" <| Array.toList matches)
```

Incorrect Html output:
```elm
ul p {query, matches} =
  Html.ul []
    <| Array.toList
    <| Array.map
        (\m -> 
          Html.li [ class' p.liClass ] [ p.config.renderItem m ]
        )
        (Debug.log "array" matches)
```

This is a function I'm using as a view for an autocomplete list. The second version of this function will often not display the first element in the array - or display only the first element from a previous array even though the array has now been emptied. In both scenarios and with both functions the debug statement always prints the correct list.

**Comment by wmatyjewicz** [comment]
I think it may be related to a bug in Array.map which has been fixed on master: elm-lang/core#171

**Comment by rehno-lindeque** [comment]
I'll try to remember to test this, thanks.

**Comment by evancz** [comment]
Any tests done here?

**Comment by rehno-lindeque** [comment]
No sorry, but this is so old... let's close it. I haven't used `Array` for some time because I don't really trust it... would be nice to have a type-checked implementation of `Array` somehow.
