### ISSUE TITLE
New line from space in h1

### ISSUE THREAD

**Issue by MangelMaxime** [evancz/elm-html#47]
I have the following code :

```
menu : Element
menu =
  flow down
    [ 
      toElement 0 0 (h1 [] [ text "My awsome title" ])
    ]
```

And here is the result :

![capture](https://cloud.githubusercontent.com/assets/4760796/6799980/b800c338-d21a-11e4-935a-061cc4d56bff.PNG)

I think normaly it should appear on only one line.

**Comment by evancz** [comment]
You are trying to put the text in a 0 by 0 box though. The size of an `Element` is known and fixed, so things inside respect those sizes. Does that clarify things?

**Comment by MangelMaxime** [comment]
Hum, yes that make sense.

I think, it would be interesting to have a way to auto size the element no ?

**Comment by evancz** [comment]
I think so as well, but I'm not sure how to do that. I want to close this issue and await a more concrete proposal about how to make that happen. Thanks for the report!
