### ISSUE TITLE
Recreates canvas from scratch every frame

### ISSUE THREAD

**Issue by archaeopterasa** [evancz/elm-html#48]
While debugging some performance issues (described at https://groups.google.com/forum/#!topic/elm-discuss/12L13sm0OZM) I found that calling fromElement on a collage results in recreating the canvas from scratch every time -- the equality check at https://github.com/evancz/virtual-dom/blob/master/src/Native/VirtualDom.js#L1126 fails because the init value returned by https://github.com/evancz/virtual-dom/blob/master/src/Native/VirtualDom.js#L1829 never matches.

(I'm filing this here rather than in virtual-dom because this is where it manifests and I don't know enough about the intended equality semantics to know which sub-library is really acting "wrong.")

Repro for this issue, checking the canvas in Chrome or adding a console.log at the point of creation confirms that it's happening every frame:
```
import Graphics.Collage (..)
import Html
import Signal
import Time

type alias Model = Int
type Action = ClockTick

main = Signal.map viewFor model

update action model = model
viewFor model = Html.fromElement <| collage 300 300 []
model = Signal.foldp update 0 time
time = Signal.map (\time -> Signal.send actionChannel ClockTick) (Time.fps 60)
actionChannel = Signal.channel ClockTick
```

**Comment by archaeopterasa** [comment]
Slight error in the example repro code: as written it *never* creates a canvas because an actual canvas element is only created the first time a drawing context is needed, which in this case is never because the collage contains no forms (it does still recreate the containing div every time though). Adding any form to the collage line will make this into a genuine repro of the original issue.

The pull request above is a candidate fix for this issue that changes the update check in virtual-dom.

**Comment by evancz** [comment]
I believe this is fixed with the latest release of virtual-dom and elm-html. Please try it out with the following program and let me know if you are seeing it resolved!

```elm
import Color exposing (red)
import Graphics.Collage exposing (..)
import Html
import Signal
import Time

type alias Model = Int
type Action = ClockTick

main = Signal.map view model

view model =
  Html.div []
    [ Html.text "Hey, does this look okay to you?"
    , Html.fromElement <|
        collage 300 300
          [ ngon 5 100
              |> filled red
              |> rotate (degrees (model / 100))
          ]
    ]

model =
  Signal.foldp (+) 0 (Time.fps 60)
```

**Comment by evancz** [comment]
The underlying has been reported a few different ways, so I'm combining them all into meta issue #80. Follow along there to see progress on this. Thanks for the report!
