### ISSUE TITLE
Simplify Html.Events API?

### ISSUE THREAD

**Issue by evancz** [evancz/elm-html#49]
With the changes coming in 0.15, it seems like a reasonable time to revisit the `Html.Events` API which is going through a major bump anyway.

Which of these versions of `onClick` seems nicer?

```elm
onClick : Signal.Address a -> a -> Attribute

onClick : Signal.Message -> Attribute
```

The benefit of the first one is that you do not need to introduce the concept of `Message` which maybe can be tricky. It also tends to be shorter because you don't have to say `Signal.message` a ton. For example:

```elm
view address =
  div []
    [ button
        [ onClick address Reset ]
        [ text "Reset" ]
    , button
        [ onClick address Increment ]
        [ text "Increment" ]
    , button
        [ onClick address Decrement ]
        [ text "Decrement” ]
    ]
```

Generally shorter.

The concept of a `Message` is actually a bit more powerful though. Here's an example for `onKeyPress`:

```elm
onKeyPress : Signal.Address a -> (Int -> a) -> Attribute

onKeyPress : (Int -> Signal.Message) -> Attribute
```

In the first one, you always send to the same address. In the second one, you can send to different addresses depending on the key.

### Proposal

We keep the type of `on` as is, with the `Signal.Message` but all the others go to the simpler type that needs fewer characters.

```elm
on : String -> Json.Decoder a -> (a -> Signal.Message) -> Attribute

onClick : Signal.Address a -> a -> Attribute
onDoubleClick : Signal.Address a -> a -> Attribute
...

onKeyUp : Address a -> (Int -> a) -> Attribute
onKeyDown : Address a -> (Int -> a) -> Attribute
...
```

How does this sound? How would this change your code?

**Comment by rtfeldman** [comment]
Definitely in favor. I like the idea of the convenience functions making the most common use case even more convenient and concise!

Here's how [some of my code](https://github.com/rtfeldman/dreamwriter/blob/master/Component/LeftSidebar.elm#L117-L145) would change, assuming it were also refactored to accept `Address Actions` instead of `Channels a`:

```elm
viewCurrentDocHeader : Doc -> Address Actions -> Html
viewCurrentDocHeader currentDoc actions =
  let downloadOptions = {
    filename    = (legalizeFilename currentDoc.title) ++ ".html",
    contentType = downloadContentType
  }
  in
    menu [id sidebarHeaderId, class sidebarHeaderClass] [
      menuitem [
        title "New",
        class "sidebar-header-control flaticon-add26",
        onClick actions NewDoc] [],
      menuitem [
        title "Open",
        class "sidebar-header-control flaticon-folder63",
        onClick actions (UpdateModel <| SetViewMode OpenMenuMode)] [],
      menuitem [
        title "Download",
        class "sidebar-header-control flaticon-cloud134",
        onClick actions (Download downloadOptions)] [],
      menuitem [
        title "Print",
        class "sidebar-header-control flaticon-printer70",
        onClick actions Print] [],
      menuitem [
        title "Settings",
        class "sidebar-header-control flaticon-gear33",
        onClick actions (UpdateModel <| SetViewMode SettingsMode)] []
    ]
```

I do think "on" feels a bit strange here...so here's how it would look with "bind" instead, which to me feels like a more natural term to fit this type signature:

```elm
viewCurrentDocHeader : Doc -> Address Actions -> Html
viewCurrentDocHeader currentDoc actions =
  let downloadOptions = {
    filename    = (legalizeFilename currentDoc.title) ++ ".html",
    contentType = downloadContentType
  }
  in
    menu [id sidebarHeaderId, class sidebarHeaderClass] [
      menuitem [
        title "New",
        class "sidebar-header-control flaticon-add26",
        bindClick actions NewDoc] [],
      menuitem [
        title "Open",
        class "sidebar-header-control flaticon-folder63",
        bindClick actions (UpdateModel <| SetViewMode OpenMenuMode)] [],
      menuitem [
        title "Download",
        class "sidebar-header-control flaticon-cloud134",
        bindClick actions (Download downloadOptions)] [],
      menuitem [
        title "Print",
        class "sidebar-header-control flaticon-printer70",
        bindClick actions Print] [],
      menuitem [
        title "Settings",
        class "sidebar-header-control flaticon-gear33",
        bindClick actions (UpdateModel <| SetViewMode SettingsMode)] []
    ]
```

**Comment by pchiusano** [comment]
Not in favor. It's only a tiny bit shorter `onClick address Reset` vs `onClick (message address Reset)`, and less expressive. The `on` function, with the explicit decoder needed, is ugly and low level IMO, so I much prefer the other functions.

**Comment by rtfeldman** [comment]
Keep in mind these are convenience functions though...they exist to make the common case maximally nice, not to maximize expressiveness.

How often in UI programming do you route to different addresses depending on the event payload? In the JS code I've encountered over the years, the `event` parameter is disregarded over 80% of the time. Almost always you're just binding to `click` in particular; when you do bind to `keyDown` and want to do something different depending on what the user typed, it's usually bound in approximately one place per page and then has a big `case` statement for handling different keyboard shortcuts - [like this](https://github.com/rtfeldman/dreamwriter/blob/master/src/Editor.coffee#L43), for example.

I'd definitely prefer to have my code less verbose than the status quo in the common case and more verbose in the edge case.

**Comment by evancz** [comment]
The point of `on` is to be able to express everything, so if someone wants a different API, it can easily be done as a package of all sorts of event handlers with all sorts of names. I can easily imagine myself creating little helpers if I need a crazier kind of behavior. For example:

```elm
on' : String -> Signal.Message -> Attribute
on' eventName message =
    on eventName Json.value (always message)
```

I also would recommend that people not use variables unqualified so I'd definitely be writing `onClick (Signal.message actions Reset)` which is quite a bit longer.

I want to veto `bind`, I don't think that is nicer. But I guess someone can make that package :) Let's see if other folks have opinions on this?

**Comment by rehno-lindeque** [comment]
I'd say that this change doesn't affect me too much because I'm already overriding events a lot of the time. Dealing with forms and all the associated weirdness to do with that, I often need to parse something out of the event structure and wrap up `on` with my own handlers anyway. I think making the default `on*` shorthands as simple as possible is a good goal (they are only shorthands after all).

**Comment by TheSeamau5** [comment]
I am in favor because I end up using `on` a lot and, so, when I need to actually do more significant stuff I use that. Or else, it's just `message`, `message`, `message` all over the place.

**Comment by evancz** [comment]
Thanks for the advice! I went for it, this will come out along with 0.15

**Comment by shashi** [comment]
One more useful model here (or in a higher-level package building on elm-html) would be to allow users to attach "behaviors" (I'm not talking about behavior as in FRP writing here, just referring to the dictionary meaning) to widgets on screen.
```
clickable [leftbutton, rightbutton] (button
    [ text "Reset" ]) address (\x -> Reset)
```
Here `x` in the lambda is the button that was pressed.

This can extend to things like `editable` (contenteditable), `draggable`, `dropzone`, `resizable` (which would probably return a signal of Html elements instead of just a single element). I think a library of such behaviors will certainly make life easier.
