### ISSUE TITLE
Events fire when they shouldn't

### ISSUE THREAD

**Issue by TheSeamau5** [evancz/elm-html#53]
It seems like events are somehow static and changing the events of an element dynamically seems broken. In this example we have a container that takes up the whole screen. This container listens to three events: mousedown, mousemove, mouseup. 

The idea is that: 
1. If the container is pressed, it can only listen to mousemove and mouseup events. 
2. If the container is not pressed, it can only listen to mousedown events. 

While, at first, the container only listens to mousedown events, it seems that as soon as the container gets clicked then it will forever listen to all three events. 

Open the console and see the actions printed to convince yourself of this behavior.

```elm
import Html 
import Html.Events 
import Html.Attributes

import Signal 
import Debug

(=>) = (,)

isPressed = False

type Action 
  = Move 
  | Up 
  | Down

view address isPressed = 
  let 
      events = 
        if isPressed 
        then 
          [ Html.Events.onMouseMove address Move
          , Html.Events.onMouseUp address Up
          ]
        else 
          [ Html.Events.onMouseDown address Down ]
          
      containerStyle = 
        [ "width" => "100vw"
        , "height" => "100vh"
        ]
  in 
      Html.div 
        ( Html.Attributes.style containerStyle :: events )
        []
          
            
            
update action isPressed = 
  case Debug.log "Action" action of 
    Up -> False
    Down -> True 
    Move -> isPressed
    
    
{address, signal} = Signal.mailbox Up

main = 
  Signal.map (view address)
    (Signal.foldp update isPressed signal)

```

**Comment by avh4** [comment]
I just ran into this too.  In my case, I had a div with onClick, and then when my model changes and I render a completely different view, one of the new div's has the onClick handler from the old div.

**Comment by evancz** [comment]
@avh4, are you using the latest release of elm-html? Is the same behavior there with 3.0.0 and 4.0.0?

**Comment by avh4** [comment]
Yes, this was with 3.0.0.

4.0.0 appears to fix it for my case.

**Comment by TheSeamau5** [comment]
Cool, the code works as expected on elm-lang/try. I'll close this issue as it seems that things got fixed.

**Comment by evancz** [comment]
Awesome, thanks for checking on this! I removed a particularly tricky dependency that was causing some other issues, so I'm glad the unintended consequences are towards things getting fixed so far :)

**Comment by tcoopman** [comment]
I just noticed this bug when using elm-reactor. When I run the compiled js code, the bug doesn't occur.
My elm-package.json say I have `"evancz/elm-html": "4.0.1 <= v < 5.0.0"`, so I find it odd that bug still occurs in elm-reactor.

**Comment by evancz** [comment]
@tcoopman, elm-reactor currently has a bad characteristic in which Elm modules needed to render the debugging sidebar can trample on Elm modules that are needed for user code. I'm not sure if this is fixed in the big overhaul of elm-reactor that's in the works, but I suspect it is. I'd look around that repo if you want to follow this up, but it is a known issue that I think it's important to fix.

**Comment by tcoopman** [comment]
@evancz thanks for the response. I'm going to take a look at elm-reactor.
