### ISSUE TITLE
preventDefault and stopPropagation support

### ISSUE THREAD

**Issue by rtfeldman** [evancz/elm-html#58]
There is currently neither a first-class way to do [`preventDefault`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) and [`stopPropagation`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) nor a good workaround (via e.g. ports).

See https://groups.google.com/forum/#!topic/elm-discuss/W3X_m1mE70w for a motivating use case.

**Comment by evancz** [comment]
Check it out! http://package.elm-lang.org/packages/evancz/elm-html/4.0.0/Html-Events#onWithOptions
