### ISSUE TITLE
Add a toString function

### ISSUE THREAD

**Issue by TheSeamau5** [evancz/elm-html#59]
The inverse of https://github.com/evancz/elm-html/issues/55

```elm
renderAsString : Html -> String 
```

Example : 

```elm
button = 
  Html.button 
       [ Html.Attributes.id "myButton" ]
       [ Html.text "Click Me" ]

renderAsString button == 
"""
<button id = "myButton"> Click Me </button>
"""
```

I see two main uses for this function: 

1. Server-side rendering
2. Testing and tooling. While it is important for the `Html` type to remain internal (due to the awesome virtual-dom magic), tools could use for great good (like checking if all the accessibility best practices were followed, etc...). 

Alternatively, it maybe interesting to be able to render Html as a union type which can easily be queried. (for example, something like the following)

```elm 
type HtmlUnion
  = Text String 
  | Element (List AttributeUnion) (List HtmlUnion)

type alias AttributeUnion = (String, String)
```

One can then imagine turning this into Json and back for use in an IDE to offer great tips.

**Comment by Raynos** [comment]
@TheSeamau5 

You can add https://github.com/nthtran/vdom-to-html to elm-html to achieve this.

**Comment by TheSeamau5** [comment]
Cool, looks like it could do just the trick. Thanks.

**Comment by gyzerok** [comment]
@TheSeamau5 did you solve that problem? If so can you share your solution through gist?

**Comment by gyzerok** [comment]
https://github.com/evancz/elm-html/pull/85

**Comment by BrianHicks** [comment]
I could really use this. I'd like to do something with static site gen in Elm, this would be quite useful. What have other people been using for this, #85?

**Comment by evancz** [comment]
I have a plan of how to do this in a good way in a future release.
