### ISSUE TITLE
Conditional preventDefault

### ISSUE THREAD

**Issue by aymanosman** [evancz/elm-html#62]
Unless I'm missing something, there seams not to be a way to conditionally 'call' preventDefault.

```elm
import Html exposing (..)
import Html.Events exposing (..)
import StartApp

main =
  StartApp.start { model = model, view = view, update = update }

model = 0

view address model =
  let options = {preventDefault = True, stopPropagation = False}
      toMessage = (\k ->
        case k of
          -- 40 is down arrow
          40 -> Signal.message address Increment -- now prevent default
          _ -> Signal.message address Decrement) -- don't want to prevent default here
  in
  div []
    [ input [onWithOptions "keydown" options keyCode toMessage] []
      , span [] [text (toString model)]
    ]

type Action = Increment | Decrement

update action model =
  case action of
    Increment -> model + 1
    Decrement -> model - 1
```

What I would like is to be able to type characters into that input while 'capturing' down arrow presses (and interpreting them in a different way). All I seam to be able to do is capture all keydown events.

Is there a way to conditionally preventDefault or uncapture event or whatever.

@evancz + Elm are awesome! I am *addicted* to writing Elm programs.

**Comment by evancz** [comment]
Thanks :D Having a way to prevent default just got added, so this may not be possible.

You used to be able to do things like this, and have stuff fall through:

```elm
view address model =
  div []
    [ input
        [ onUp address Increment
        , onKeyDown address (always Decrement)
        ]
        []
    , span [] [text (toString model)]
    ]



onUp : Address a -> a -> Attribute
onUp address value =
    onWithOptions
      { preventDefault = True, stopPropagation = False }
      "keydown"
      (Json.customDecoder keyCode isUp)
      (\_ -> Signal.message address value)


isUp : Int -> Result String ()
isUp code =
  if code == 40 then Ok () else Err "not the right key code"
```

I'm not certain if that is still possible. If not, can you say more about exactly why you want to `preventDefault` in one case but not the other?

**Comment by rehno-lindeque** [comment]
I wouldn't point this out as the nicest piece of code I've ever written (I decided it's a bit too hacky to add to our `elm-html-extra`) but I sort of did something vaguely similar over here: 

https://github.com/circuithub/elm-html-shorthand/blob/edad2a85d36883d2dc50351e9304222cd3c23cb0/src/Html/Shorthand/Event.elm#L78

Like @evancz says, the trick is to write your own `Json.customDecoder` for the event and then rely on `Err` to filter out keystrokes or any other conditions in the event data.

**Comment by aymanosman** [comment]
Perfect! `Json.customDecoder` did the trick.

```elm
view address model =
  let
    onArrow addr =
      onWithOptions "keydown" {preventDefault = True, stopPropagation = False}
      (Json.customDecoder keyCode isArrow)
      (\k ->
          Signal.message addr <|
          case k of
            40 -> Decrement
            38 -> Increment
            _ -> NoOp)
    isArrow =
      (\k ->
        if k == 40 || k == 38
        then Ok k
        else Err "not arrow")
  in
  div []
    [ input 
        [ onArrow address ] []
      , span [] [text (toString model)]
    ]
```

It wasn't clear to me to reach for the Decoder as it did not occur to me that if it failed the event would 'fall through'. Maybe an example in the docs showing the use of `Json.customDecoder` would be useful here http://package.elm-lang.org/packages/evancz/elm-html/4.0.1/Html-Events?

**Comment by ThomasCrvsr** [comment]
Hello !

I came to this issue because I have the same kind of problem but I'm not sure the solution given here could be applied for my case.

Basically, I've a textarea and I want a normal behaviour while typing but pressing ctrl + enter would trigger a special action and call preventDefault.

**Comment by wmakley** [comment]
I have the same issue with a text box. Certain key events we want to ignore, others we want to pass through. No way to do that right now unless I re-implement all the functionality of the keypress event in elm, so the only solution is jQuery and a port.

**Comment by aymanosman** [comment]
@ThomasCrvsr, @wmakley I had to quickly change this code to work on the online elm try website (because the start-app package was updated from 1.0 to 2.0), but it works and demonstrates using a customDecoder to capture the events you are interested in.

https://gist.github.com/aymanosman/2a82c55ed86e5ecc904f#file-elm-events-elm-L92

You should be able to paste that code into http://elm-lang.org/try and see it work.

* Type "an" to see a list of candidates
* Press Up and down arrows to highlight a candidate.
* Press Enter to select.

The default behaiviour of Up and Down are suppressed (would normally move the cursor in the input box).

I know that its a lot of code to demonstrate such a small thing, but it was the only example I had at hand. Hope that helps.
