### ISSUE TITLE
Html.lazy does not work as intended

### ISSUE THREAD

**Issue by rhaps0dy** [evancz/elm-html#63]
For example this code:

```elm
import Html.Lazy exposing (lazy)
import Html exposing (p, text, Html)
import Signal exposing (Signal, (~), (<~))
import Signal
import Time
import Time exposing (Time)
import Debug

render : Int -> Html
render n =
 let
   dummy = Debug.log "Rendered" ""
 in
   p [] [text <| toString n]

main : Signal Html
main = lazy render <~ Signal.sampleOn (Time.every Time.second) (Signal.constant 1234)
```

prints out "Rendered" every second, and it should not. See the [thread from the mailing list](https://groups.google.com/forum/?fromgroups#!searchin/elm-discuss/lazy/elm-discuss/qwU2ha9z3S4/q2K9H1NxK1kJ)

**Comment by evancz** [comment]
This has been fixed in virtual-dom. Thanks for reporting this!

**Comment by evancz** [comment]
The fixed version should be out in the next week or two.
