### ISSUE TITLE
title in Html.Attributes seems to be expecting different parameters

### ISSUE THREAD

**Issue by bbugh** [evancz/elm-html#69]
I was testing using the `title` attribute from `Html.Attributes` and it seems to not work.

The docs say it takes a `String` and resolves an `Attribute`

```
title : String -> Attribute
      Text to be displayed in a tooltip when hovering over the element.
```

However, if I do a basic test with title, the compiler complains that 

```no-highlight
117|       [ id "container", title "Test" ]
                             ^^^^^^^^^^^^
All elements should be the same type of value so that we can iterate over the
list without running into unexpected values.

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Attribute

    Int -> Html Use --force to continue.
```

**The code for `title` looks exactly the same as the code for `id` in `Html/Attributes.elm` so I'm not sure why it's happening.** 

```elm
{-| Often used with CSS to style a specific element. The value of this
attribute must be unique.
-}
id : String -> Attribute
id name =
  stringProperty "id" name


{-| Text to be displayed in a tooltip when hovering over the element. -}
title : String -> Attribute
title name =
  stringProperty "title" name
```

Sorry if it's a misunderstanding on my part, but it seems like a bug.

**Comment by bbugh** [comment]
The only thing I can think of is that `title` is defined in another module? Here's my imports:

```elm
import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (..)
import String
import StartApp
```

**Comment by evancz** [comment]
Do you have something called `title` defined in your module?

We *should* be detecting name collisions if there are multiple versions of `title` imported. But if you define `title` locally, it just takes precedence over everything. Could that be it?

**Comment by bbugh** [comment]
Dang, that was it.  Every day I tell people "always check your assumptions". I'm overthinking it since I'm learning. Thanks for the quick reply and sorry for the waste of time. Elm is amazing. :+1:

**Comment by evancz** [comment]
No worries, glad we got it sorted out!

Glad you are liking it, and let us know if you run into anything else! :)

**Comment by bbugh** [comment]
If you don't mind, what's the "best practice" option for this use case?

1. specifically import `Html.Attributes.title` with an alias? (somehow)
2. Just know to avoid namespace collisions when like defining `title` when I'm importing with `(..)`? 
3. Or simply to reference by full namespace and call it a day?

```elm
  div [ id "container", Html.Attributes.title "Test" ]
```

**Comment by evancz** [comment]
The following import syntax is probably what I'd go for:

```elm
import Html as H exposing (..)
import Html.Attribute as A exposing (..)

   div [ id "container", A.title "Test" ]
```

So that syntax lets you alias the module name with something shorter. `A` is probably shorter than you'd want in professional grade code, but I use it in my own stuff :)
