### ISSUE TITLE
Unify two styles

### ISSUE THREAD

**Issue by sindikat** [evancz/elm-html#72]
Suppose I have a view function:

    view =
      let
        style1 = Html.Attributes.style [ ("width", "20px"), ("height", "20px") ]
        style2 = Html.Attributes.style [ ("background-color", "#ff0000") ]
      in
        Html.div [ style1, style2 ] [ Html.text "some text" ]

`style2` overrides `style1`, `style1` just isn't used. Once you already converted list of pairs into `Html.Attribute`, there's no way you can unify these two styles into one. It would be nice if there a way to combine several styles into one, with latter styles in a list taking precedence for the same CSS attributes.

**Comment by evancz** [comment]
One thing you can do is just define the styles as lists for now. Then you can put them together with `(++)`.

```elm
import Html exposing (div, text)
import Html.Attributes exposing (style)

view =
  let
    style1 = [ ("width", "20px"), ("height", "20px") ]
    style2 = [ ("background-color", "#ff0000") ]
  in
    div [ style (style1 ++ style2) ] [ text "some text" ]
```

There is an idea to make it easier to nest things without having to use `(++)` but that will probably need to wait on a totally new version of this library.
